<?php
use Zend\Authentication\AuthenticationService;
echo $this->doctype ();
?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate(APP_NAME))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php
		$headLink = $this->headLink ( array (
			'rel' => 'shortcut icon',
			'type' => 'image/vnd.microsoft.icon' 
		) );
		$headLink->prependStylesheet ( $this->basePath () . '/css/style.css' );
		$headLink->prependStylesheet ( $this->basePath () . '/css/flat-bootstrap-theme.css' );
		$headLink->prependStylesheet ( $this->basePath () . '/css/bootstrap-datetimepicker.css' );
		$headLink->prependStylesheet ( $this->basePath () . '/css/fuelux.css' );
		$headLink->prependStylesheet ( "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" );
		$headLink->prependStylesheet ( "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" );
		echo $headLink;
		?>
          
        <!--[if IE 7]>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome-ie7.min.css">
<![endif]-->

<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<!-- Scripts -->
        
        <?php
		$headScript = $this->headScript ();
		$headScript->prependFile ( $this->basePath () . '/js/jquery.ajax-form-submit.js' );
		$headScript->prependFile ( $this->basePath () . '/js/bootstrap-wizard.js' );
		$headScript->prependFile ( $this->basePath () . '/js/bootstrap-datetimepicker.js' );
		$headScript->prependFile ( $this->basePath () . '/js/noty/packaged/jquery.noty.packaged.min.js' );
		$headScript->prependFile ( "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" );
		$headScript->prependFile ( "//code.jquery.com/jquery-1.11.3.min.js" );
		$headScript->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
			'conditional' => 'lt IE 9' 
		) );
		$headScript->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
			'conditional' => 'lt IE 9' 
		) );
		echo $headScript;
		
		?>
		<script src="//www.fuelcdn.com/fuelux/3.6.3/js/fuelux.min.js"></script>

</head>

<style>
.brand-one, .brand-two {
font-family: 'Open Sans Condensed', sans-serif;
	font-size: 32px;
}
.navbar-brand{
	padding-top:12px;
}

.brand-one {
	color: #eeb085;
}

.brand-two {
	color: #16A0c5;
}

.wizard .step-content {
	background-color: #fff;
}

body {
	background-color: #ecf0f1;
}
</style>

<body class="fuelux">
<?php
// get service locator
$sl = $this->viewmodel ()->getView ()->getHelperPluginManager ()->getServiceLocator ();

// $UserTable = $sl->get('Model\Entity\User');
$Auth = new AuthenticationService ();
// check has identity, else Tests cases will fail
if ($Auth->hasIdentity ()) {
	$AuthStorage = $Auth->getStorage ()->read ();
	// echo $AuthStorage->username;
}

?>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><span
					class="brand-one">key</span><span class="brand-two">,par</span>
				</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
				<?php if($Auth->hasIdentity()){?>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signin','action'=>'quit')) ?>"> <?php echo $this->translate('Sign Out') ?></a></li>
					<?php } else {?>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signin')) ?>"> <?php echo $this->translate('Sign In') ?></a></li>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signup')) ?>"> <?php echo $this->translate('Sign Up') ?></a></li>
					<?php } ?>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container-fluid">
		<div class='row'>
			<div class='col-md-12'>
                <?php echo $this->partial('flash-messages'); ?>
                  <br>  
    	        <?php echo $this->layout()->content; ?>
	        </div>
		</div>
		<div class='row'>
			<div class='col-md-12 '>
				<hr>
				<footer>
					<br> <br>
					<p>&copy; <?php echo date('Y') ?>. <?php echo $this->translate('All rights reserved.')?> <?php echo APP_NAME?>
					</p>
					<br> <br> <br> <br>
				</footer>
			</div>
		</div>
	</div>
	<!-- /container -->
    <?php echo $this->inlineScript()?>
    </body>
</html>


<script>

function showNoty(type,message){
	
	noty({
	    layout: 'topCenter',
	    theme: 'relax', // or 'relax'
	    type: type,
	    timeout:5000,
	    closeWith: ['click'],
	    text: message,
	    dismissQueue: true, // If you want to use queue feature set this true
		animation: {
	        open: {height: 'toggle'}, // jQuery animate function property object
	        close: {height: 'toggle'}, // jQuery animate function property object
	        easing: 'swing', // easing
	        speed: 300 // opening & closing animation speed
	    }
	});
}
</script>
